NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-hla-org-com-9054-ca-hla.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-hla-org-com-9054-ca-hla.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-hla-org-com-9054-ca-hla.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-hla-org-com-9054-ca-hla.pem
    OrganizationalUnitIdentifier: orderer
