NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-viamed-org-com-10054-ca-viamed.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-viamed-org-com-10054-ca-viamed.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-viamed-org-com-10054-ca-viamed.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-viamed-org-com-10054-ca-viamed.pem
    OrganizationalUnitIdentifier: orderer
