NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-sas-org-com-7054-ca-sas.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-sas-org-com-7054-ca-sas.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-sas-org-com-7054-ca-sas.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-sas-org-com-7054-ca-sas.pem
    OrganizationalUnitIdentifier: orderer
