version: "3.2"

networks:
  mynetwork:
    external:
      name: mynetwork

services:
  api:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
         constraints:
           - node.hostname == manager
    image: api_fabric_sdk:1.0
    ports:
      - 4000:4000
    extra_hosts:
      - "ca.sas.org.com:172.16.17.11"
      - "ca.quiron.org.com:172.16.17.11"
      - "ca.hla.org.com:172.16.17.11"
      - "ca.viamed.org.com:172.16.17.11"
      - "ca.orderer.org.com:172.16.17.11"
      - "orderer.org.com:172.16.17.11"
      - "peer0.sas.org.com:172.16.17.11"
      - "peer0.hla.org.com:172.16.17.12"
      - "peer0.viamed.org.com:172.16.17.12"
      - "peer0.quiron.org.com:172.16.17.12"
    networks:
      mynetwork:
        aliases:
          - api.fabric.sdk