NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-quiron-org-com-8054-ca-quiron.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-quiron-org-com-8054-ca-quiron.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-quiron-org-com-8054-ca-quiron.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-quiron-org-com-8054-ca-quiron.pem
    OrganizationalUnitIdentifier: orderer
